FROM esztiorm/0636920105954:latest

USER root
# install git for pulling HEAP necessary packages
RUN  apt-get install git --yes
# notebook and ipykernel should already be installed. now just need jupyterhub
RUN pip install --upgrade --no-cache-dir jupyterhub

USER jovyan

WORKDIR /home/jovyan
# adding oneliner for css stuff
RUN echo "@import url(\"https://cdn.oreillystatic.com/jupyterhub/jupyterhub-theme/custom/custom.css\")" >> /opt/conda/lib/python3.6/site-packages/notebook/static/custom/custom.css

RUN pip install git+http://github.com/oreillymedia/nbheapanalytics@c1991d9f03682
RUN jupyter nbextension install --py --sys-prefix nbheapanalytics
RUN jupyter nbextension enable --py --sys-prefix nbheapanalytics
RUN jupyter serverextension enable --sys-prefix nbheapanalytics

# the HEAP id number may change, but for now is same for everything
CMD jupyterhub-singleuser \
  --port=8888 \
  --ip=0.0.0.0 \
  --user="$JPY_USER" \
  --cookie-name=$JPY_COOKIE_NAME \
  --base-url=$JPY_BASE_URL \
  --hub-prefix=$JPY_HUB_PREFIX \
  --hub-api-url=$JPY_HUB_API_URL \
  --HeapAnalytics.tracking_id="\"1702831224\""
